apiVersion: v1
kind: Service
metadata:
  name: doctor
  labels:
    app: doctor
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: doctor
